name: CI Pipeline

on: [push]

jobs:
  build_and_test_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install scikit-learn joblib

      - name: Train model
        run: python train.py

      - name: Build Docker image
        run: docker build -t mlops-assignment3 .

      - name: Run container
        run: docker run mlops-assignment3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image to DockerHub
        run: |
          docker tag mlops-assignment3 ${{ secrets.DOCKER_USERNAME }}/mlops-assignment3
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-assignment3
